export const ACTIONS = {
  START_SCAN: 'START_SCAN',
  LOCK_IDENTITY: 'LOCK_IDENTITY',
  MESH_LOADED: 'MESH_LOADED',
  FINISH: 'FINISH',
  RESET: 'RESET'
};

export const STATUS = {
  READY: 'READY',
  SCANNING: 'SCANNING',
  LOCKED: 'LOCKED',
  SNAP_READY: 'SNAP_READY'
};

export const IDENTITY = {
  LILA_INICIAL: '#C8A2C8',
  ROJO_VALENTINO: '#E60000'
};

export const SNAP_TIMING_MS = {
  LOCK_IDENTITY: 2000,
  FINISH: 3500
};
